import { NavigationGroupMeta, NavigationItem } from "../types/navigation";

export const NAVIGATION_GROUPS: Record<string, NavigationGroupMeta> = {
  main: {
    id: "main",
    label: "Overview",
    order: 1,
  },
  business: {
    id: "business",
    label: "Business & Clients",
    order: 2,
  },
  catalog: {
    id: "catalog",
    label: "Catalog & Goods",
    order: 3,
  },
  insights: {
    id: "insights",
    label: "Financials & Insights",
    order: 4,
  },
  operations: {
    id: "operations",
    label: "Fulfillment & Care",
    order: 5,
  },
  system: {
    id: "system",
    label: "Console System",
    order: 6,
  },
};

export const MASTER_NAVIGATION: NavigationItem[] = [
  {
    id: "home",
    label: "Home",
    shortLabel: "Home",
    iconName: "Home",
    href: "/",
    permission: "home.read",
    feature: null,
    group: "main",
    mobilePriority: 1,
    mobile: {
      primary: true,
    },
    description: "Executive summary, daily order volumes, and studio highlights",
    keywords: ["dashboard", "overview", "home", "stats", "kpi"],
  },
  {
    id: "orders",
    label: "Orders & Pipeline",
    shortLabel: "Orders",
    iconName: "ShoppingBag",
    href: "/orders",
    permission: "orders.read",
    feature: "orders_kanban",
    group: "business",
    mobilePriority: 2,
    mobile: {
      primary: true,
    },
    badge: "12",
    badgeVariant: "accent",
    description: "Manage client purchases, Kanban processing board, and order tickets",
    keywords: ["orders", "kanban", "tickets", "fulfillment", "purchases"],
  },
  {
    id: "catalog",
    label: "Catalog & Products",
    shortLabel: "Catalog",
    iconName: "Layers",
    href: "/catalog",
    permission: "catalog.read",
    feature: "catalog",
    group: "catalog",
    mobilePriority: 3,
    mobile: {
      primary: true,
    },
    description: "Luxury apparel, lookbooks, sizes, material inventory, and SKUs",
    keywords: ["catalog", "products", "apparel", "angora", "garments", "bags", "shoes"],
  },
  {
    id: "revenue",
    label: "Revenue & Ledger",
    shortLabel: "Revenue",
    iconName: "CircleDollarSign",
    href: "/revenue",
    permission: "revenue.read",
    feature: "revenue",
    group: "insights",
    mobilePriority: 4,
    mobile: {
      // Primary when permitted, will take 4th slot if authorized
      primary: true,
    },
    badge: "+18%",
    badgeVariant: "subtle",
    description: "Gross revenue breakdown, currency settlement, and sales performance",
    keywords: ["revenue", "money", "sales", "finance", "earnings", "profit"],
  },
  {
    id: "customers",
    label: "Customers & Clients",
    shortLabel: "Clients",
    iconName: "Users",
    href: "/customers",
    permission: "customers.read",
    feature: null,
    group: "business",
    mobilePriority: 5,
    mobile: {
      primary: false,
    },
    description: "VIP patron profiles, order histories, styling notes, and contacts",
    keywords: ["customers", "clients", "vip", "profiles", "patrons", "contacts"],
  },
  {
    id: "delivery",
    label: "Delivery & Tracking",
    shortLabel: "Delivery",
    iconName: "Truck",
    href: "/delivery",
    permission: "delivery.read",
    feature: "delivery_tracking",
    group: "operations",
    mobilePriority: 6,
    mobile: {
      primary: false,
    },
    badge: "5 In-Transit",
    description: "Carrier dispatch (DHL, FedEx, BlueDart), parcel tracking, and transit logs",
    keywords: ["delivery", "tracking", "courier", "shipping", "dhl", "fedex", "parcels"],
  },
  {
    id: "chat",
    label: "Customer Chat",
    shortLabel: "Chat",
    iconName: "MessageCircle",
    href: "/chat",
    permission: "chat.read",
    feature: "chat",
    group: "operations",
    mobilePriority: 7,
    mobile: {
      primary: false,
    },
    description: "Client conversations, shared photos, files, and order-linked attachments",
    keywords: ["chat", "messages", "conversations", "support", "photos", "files"],
  },
  {
    id: "transactions",
    label: "Transactions",
    shortLabel: "Payments",
    iconName: "ArrowLeftRight",
    href: "/transactions",
    permission: "transactions.read",
    feature: null,
    group: "insights",
    mobilePriority: 8,
    mobile: {
      primary: false,
    },
    description: "Payment records, transaction references, and settlement log",
    keywords: ["transactions", "payments", "refunds", "settlement", "ledger"],
  },
  {
    id: "updates",
    label: "Updates Feed",
    shortLabel: "Updates",
    iconName: "Bell",
    href: "/updates",
    permission: "home.read",
    feature: null,
    group: "main",
    mobilePriority: 12,
    mobile: {
      primary: false,
    },
    description: "Live audit trail of every change, who made it, and when",
    keywords: ["updates", "activity", "audit", "notifications", "feed", "history"],
  },
  {
    id: "employees",
    label: "Employees & Staff",
    shortLabel: "Team",
    iconName: "Contact",
    href: "/employees",
    permission: "employees.read",
    feature: null,
    group: "system",
    mobilePriority: 13,
    mobile: {
      primary: false,
    },
    description: "Atelier staff directory and change attribution",
    keywords: ["employees", "staff", "team", "people", "tailors"],
  },
  {
    id: "analytics",
    label: "Analytics & Trends",
    shortLabel: "Analytics",
    iconName: "BarChart3",
    href: "/analytics",
    permission: "analytics.read",
    feature: "analytics",
    group: "insights",
    mobilePriority: 9,
    mobile: {
      primary: false,
    },
    description: "Conversion funnels, average order value, and cohort retention charts",
    keywords: ["analytics", "charts", "trends", "conversion", "retention"],
  },
  {
    id: "reports",
    label: "Executive Reports",
    shortLabel: "Reports",
    iconName: "FileSpreadsheet",
    href: "/reports",
    permission: "reports.read",
    feature: "reports",
    group: "insights",
    mobilePriority: 10,
    mobile: {
      primary: false,
    },
    description: "Exportable financial statements, GST/VAT reconciliation, and audit archives",
    keywords: ["reports", "export", "pdf", "csv", "audit", "taxes"],
  },
  {
    id: "settings",
    label: "Settings & Access",
    shortLabel: "Settings",
    iconName: "Settings",
    href: "/settings",
    permission: "settings.read",
    feature: null,
    group: "system",
    mobilePriority: 11,
    mobile: {
      primary: false,
    },
    description: "RBAC permissions matrix, feature flags simulator, and studio settings",
    keywords: ["settings", "rbac", "permissions", "flags", "roles", "config"],
  },
];
